name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: testing, DOCKER_RUN_OPTS: "-e EMSDK -e EM_CONFIG -e EM_CACHE -e EMSDK_NODE -v ${EMSDK}:${EMSDK}", UPSTREAM_WORKSPACE: "sam_webgui.rosinstall -sam_webgui"}
          - {ROS_DISTRO: melodic, ROS_REPO: main, DOCKER_RUN_OPTS: "-e EMSDK -e EM_CONFIG -e EM_CACHE -e EMSDK_NODE -v ${EMSDK}:${EMSDK}", UPSTREAM_WORKSPACE: "sam_webgui.rosinstall -sam_webgui"}
          - {ROS_DISTRO: melodic, ROS_REPO: main, CMAKE_ARGS: "-DROSWASM_NATIVE=ON", ADDITIONAL_DEBS: "libsdl2-image-dev", UPSTREAM_WORKSPACE: "sam_webgui.rosinstall -sam_webgui"}
          - {ROS_DISTRO: melodic, ROS_REPO: main, UPSTREAM_WORKSPACE: "sam_webgui.rosinstall -sam_webgui"}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: mymindstorm/setup-emsdk@v7
        with:
          version: '2.0.7'
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
